"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
if os.path.isfile('env.py'):
    import env

import blog
# middleware.py  (create this file in your project)
from django.http import HttpResponse
import re

# Common paths bots hammer
SCANNER_PATHS = [
    r'^/home/admin',
    r'^/wp-',
    r'^/phpmyadmin',
    r'^/administrator',
    r'^/laravel',
    r'^/adminer',
    r'^/cgi-bin',
    r'^/\.env',
    r'^/webadmin',
]

class BlockScannerMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        self.patterns = [re.compile(p, re.IGNORECASE) for p in SCANNER_PATHS]

    def __call__(self, request):
        path = request.path

        # Check if the path matches a known scanner pattern
        if any(pattern.search(path) for pattern in self.patterns):
            user_agent = request.META.get('HTTP_USER_AGENT', '').lower()
            referer = request.META.get('HTTP_REFERER', '')

            # Let through if:
            # - It's you (logged into Django admin)
            # - Or it's a real browser with proper headers
            # - Or request comes from localhost/heroku internal
            if (
                request.user.is_authenticated  # you're logged in as staff
                or 'heroku' in request.META.get('HTTP_X_FORWARDED_FOR', '')
                or 'mozilla' in user_agent or 'chrome' in user_agent or 'safari' in user_agent
                or 'google' in referer.lower()
            ):
                # Let your request pass normally
                pass
            else:
                # Bot-like request → silent drop or 403
                return HttpResponse(status=444)  # or 403, 410, etc.

        return self.get_response(request)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.herokuapp.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'about',
]

MIDDLEWARE = [
    'codestarblog.middleware.BlockScannerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codestarblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codestarblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
database_url = os.environ.get('DATABASE_URL')
if database_url and database_url.strip():
    DATABASES['default'] = dj_database_url.parse(database_url)



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # important for Heroku

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF trusted origins — needed for the admin to work properly
CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net",
    "https://*.herokuapp.com",
    "http://localhost:8000",          # ← add this for local dev
    "http://127.0.0.1:8000",          # ← and this one too
]